### ISSUE TITLE
can't install openssl@1.0

### ISSUE THREAD

**Issue by jack338c** [sidneys/homebrew-homebrew#20]
my macos is verntrua 13.3.1 (a) ,I can install openssl@1.0 on my macos(13.1)successfully 6 months agao
now I can't make it ,have tried roll back to macos(13.1),and reinstall macos many times,but it's still no luck.

Someone please help me.
thank you in advance !

`jack6@jack6s-Mac-mini ~ % brew install sidneys/homebrew/openssl@1.0 or brew install rbenv/tap/openssl@1.0

==> Fetching sidneys/homebrew/openssl@1.0
==> Downloading https://gist.githubusercontent.com/felixbuenemann/5f4dcb30ebb3b86e1302e2ec305bac89/raw/b339a33ff072c9747df21e2558c36634dd62c19
Already downloaded: /Users/jack6/Library/Caches/Homebrew/downloads/db281f2b8a51c8a97d6bced562e99959b2c8b3241129895f8850506ccd1f8899--openssl-1.0.2u-darwin-arm64.patch
==> Downloading https://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz
Already downloaded: /Users/jack6/Library/Caches/Homebrew/downloads/6a06bfa556bd474c7e4efb2eab11c7d43d4238b508bd91e74c438653e24b8a45--openssl-1.0.2u.tar.gz
==> Installing openssl@1.0 from sidneys/homebrew
==> Patching
==> Applying openssl-1.0.2u-darwin-arm64.patch
patching file Configure
==> perl ./Configure --prefix=/usr/local/Cellar/openssl@1.0/1.0.2u_1 --openssldir=/usr/local/etc/openssl@1.0 no-ssl2 no-ssl3 no-zlib shared en
==> make
==> make test
Last 15 lines from /Users/jack6/Library/Logs/Homebrew/openssl@1.0/03.make:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
140704691860460:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
140704691860460:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
140704691860460:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
make[1]: *** [test_ec] Error 1
make: *** [tests] Error 2`

**Comment by faisalmemon** [comment]
I also reproduce the same problem using macOS 13.2.1 (22D68)
from command
```
brew tap sidneys/homebrew
brew install cabextract wimlib cdrtools sidneys/homebrew/chntpw
```

But I actually already have version 3
```
brew install openssl
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################ 100.0%
Warning: openssl@3 3.1.0 is already installed and up-to-date.
To reinstall 3.1.0, run:
  brew reinstall openssl@3
```

**Comment by wy555** [comment]
Yes, the latest openssl is version 3.
$ /opt/homebrew/bin/brew install openssl
Warning: openssl@3 3.1.0 is already installed and up-to-date.
To reinstall 3.1.0, run:
  brew reinstall openssl@3
  
  But it did not resolve the original issue.
  The issue is due to the dependancy of  sidneys/homebrew/chntpw
  which is openssl@1.0 and not version 3
  
  ==> Fetching dependencies for sidneys/homebrew/chntpw: sidneys/homebrew/openssl@1.0
==> Fetching sidneys/homebrew/openssl@1.0
==> Downloading https://gist.githubusercontent.com/felixbuenemann/5f4dcb30ebb3b86e1302e2ec305bac89/raw/b339a33ff072c9747df21e2558c36634dd6
Already downloaded: /Users/waynekan/Library/Caches/Homebrew/downloads/db281f2b8a51c8a97d6bced562e99959b2c8b3241129895f8850506ccd1f8899--openssl-1.0.2u-darwin-arm64.patch
==> Downloading https://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz
Already downloaded: /Users/waynekan/Library/Caches/Homebrew/downloads/6a06bfa556bd474c7e4efb2eab11c7d43d4238b508bd91e74c438653e24b8a45--openssl-1.0.2u.tar.gz
==> Fetching sidneys/homebrew/chntpw
==> Downloading https://github.com/sidneys/chntpw/archive/0.99.6.tar.gz
Already downloaded: /Users/waynekan/Library/Caches/Homebrew/downloads/dee692592b6fc0d6db43012210cf70e9ef7a6018e20818b5f15187cbd3a06e39--chntpw-0.99.6.tar.gz
==> Installing chntpw from sidneys/homebrew
==> Installing dependencies for sidneys/homebrew/chntpw: sidneys/homebrew/openssl@1.0
==> Installing sidneys/homebrew/chntpw dependency: sidneys/homebrew/openssl@1.0
==> Patching
==> Applying openssl-1.0.2u-darwin-arm64.patch
patching file Configure
==> perl ./Configure --prefix=/opt/homebrew/Cellar/openssl@1.0/1.0.2u_1 --openssldir=/opt/homebrew/etc/openssl@1.0 no-ssl2 no-ssl3 no-zlib
==> make
==> make test
Last 15 lines from /Users/waynekan/Library/Logs/Homebrew/openssl@1.0/03.make:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:100B906B:elliptic curve routines:EC_POINT_set_affine_coordinates_GF2m:point is not on curve:ec_lib.c:994:
8409226220:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
8409226220:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
8409226220:error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve:ec_lib.c:968:
make[1]: *** [test_ec] Error 1
make: *** [tests] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/sidneys/homebrew-homebrew/issues

These open issues may also help:
can't install openssl@1.0 https://github.com/sidneys/homebrew-homebrew/issues/20
Mac M1 chntpw not building (Openssl 1.0 requirement not satisfied) https://github.com/sidneys/homebrew-homebrew/issues/2

Issue still not resolved.

**Comment by kim1124** [comment]
I too am having the same problem.

**Comment by faisalmemon** [comment]
Someone posted a solution at:
https://github.com/sidneys/homebrew-homebrew/issues/2#issuecomment-976440568

**Comment by goooodday** [comment]
solved problem...

https://github.com/sidneys/homebrew-homebrew/issues/2#issuecomment-885728072
